version: "3.8"

services:
  handbook:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    user: "${UID:-1000}:${GID:-1000}" # podman requires user UID and GID to be set
    volumes:
      - handbook-node-modules:/src/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - HOME=/tmp

volumes:
  handbook-node-modules:
    driver: local
