name: pull request

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    outputs:
      cache_key: ${{ steps.cache_key.outputs.cache_key }}

    steps:
      - uses: actions/checkout@v6
      - id: cache_key
        run: echo "cache_key=${{ hashFiles('**/**') }}-v1" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        id: cache
        with:
          path: node_modules
          key: ${{ steps.cache_key.outputs.cache_key }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build site
        env:
          ELEVENTY_ENV: production
        run: npm run build
      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  validate_html:
    needs: [build]
    name: validate html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: node_modules
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: HTML count
        run: find _site -name '*.html' | wc -l
      - run: npm run test:html-validation

  validate_internal_links:
    needs: [build]
    name: validate internal links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: node_modules
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: HTML count
        run: find _site -name '*.html' | wc -l
      - run: npm run test:internal-links

  validate_external_links:
    needs: [build]
    name: validate external links (linkinator)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: node_modules
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: Install dependencies
        run: npm ci
      - name: Run Linkinator
        run: npm run test:linkinator
        continue-on-error: false

  validate_links_use_helper:
    needs: [build]
    name: validate links use helper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: node_modules
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - run: npm run test:prefixed-links

  check_spelling:
    needs: [build]
    name: "Check Spelling"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          key: ${{ needs.build.outputs.cache_key }}
          path: node_modules
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site
      - name: Install cSpell
        run: npm run test:spelling
