name: "Terraform manages Teams"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for requesting the JWT

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
        
    - name: Configure GitHub token
      run: |
        # Mask the token to prevent it from showing in logs
        echo "::add-mask::${{ secrets.TF_GITHUB_TOKEN }}"
        # Set the token as an environment variable for Terraform
        echo "GITHUB_TOKEN=${{ secrets.TF_GITHUB_TOKEN }}" >> $GITHUB_ENV
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Format
      run: terraform fmt -check
      
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan
      
    # Only apply changes when PR touches terraform and when merged to main
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

